### ISSUE TITLE
ReadTheDocs not building

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#628]
ReadTheDocs build not working due to need to import sphinxcontrib-contentui added in #627. 

There seems to be an issue with running `./requirements_txt_checker.sh` reporting error:

```
$ ./requirements_txt_checker.sh
Flattening transitive dependencies of 'requirements.txt' to a temporary file '/var/folders/rk/cn5lpv2s2g1cwplxcrdxzj1r0000gn/T/tmp.bj9aEzeT'
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/piptools/scripts/compile.py", line 352, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/site-packages/piptools/resolver.py", line 119, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.7/site-packages/piptools/resolver.py", line 217, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/usr/local/lib/python3.7/site-packages/piptools/resolver.py", line 217, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/usr/local/lib/python3.7/site-packages/piptools/resolver.py", line 291, in get_best_match
    ireq, prereleases=self.prereleases
  File "/usr/local/lib/python3.7/site-packages/piptools/repositories/local.py", line 63, in find_best_match
    return self.repository.find_best_match(ireq, prereleases)
  File "/usr/local/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 147, in find_best_match
    best_candidate = max(matching_candidates, key=self.finder._candidate_sort_key)
AttributeError: 'PackageFinder' object has no attribute '_candidate_sort_key'
```

**Comment by JoshData** [comment]
It's actually working fine for me, so we'll need to get on a call some time this week.

**Comment by gregelin** [comment]
@JoshData If everything working for you, could you please make the following change to in `requirements.in` and build the `requirements.txt` file for a PR to the current master?

```
# Documentation only
m2r # MIT License
sphinxcontrib-contentui # MIT License
```

**Comment by peterkaminski** [comment]
Greg and I are trying this now on my machine.

**Comment by peterkaminski** [comment]
Created PR #629.

I ended up doing the work on a clean Ubuntu 18.04 machine, will document the process of getting that to work elsewhere.

**Comment by gregelin** [comment]
@peterkaminski Thanks. Docs now building correctly.

I made an additional set of tweaks to documents if you could review please in PR #630
