### ISSUE TITLE
populate command does not work correctly in 0.9.0.dev

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#716]
Tried running `.quickstart.sh` in 0.9.0.dev and `populate` created and error. Running populate command in 0.9.0.dev causes error.

```
$ python3 manage.py populate --full --password xxxxxxxxxxx
Created portfolio for user Kaseem
Created portfolio for user Carson
Created portfolio for user Amena
Created portfolio for user Roanna
Created portfolio for user Hayley
Admin for Sway Snuff Org: Carson
Adding system... org.slug
GET on: </store>
Traceback (most recent call last):
  File "/Users/greg/Library/Python/3.7/lib/python/site-packages/django/contrib/messages/api.py", line 21, in add_message
    messages = request._messages
AttributeError: 'WSGIRequest' object has no attribute '_messages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/greg/Library/Python/3.7/lib/python/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/greg/Library/Python/3.7/lib/python/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/greg/Library/Python/3.7/lib/python/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/greg/Library/Python/3.7/lib/python/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/codedata/code/govready-q-0.9.0-module-nav/testmocking/management/commands/populate.py", line 52, in handle
    call_command('add_system', '--username', admin.username, '--org', org.slug)
  File "/Users/greg/Library/Python/3.7/lib/python/site-packages/django/core/management/__init__.py", line 141, in call_command
    return command.execute(*args, **defaults)
  File "/Users/greg/Library/Python/3.7/lib/python/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/codedata/code/govready-q-0.9.0-module-nav/testmocking/management/commands/add_system.py", line 25, in handle
    self.client.add_system()
  File "/codedata/code/govready-q-0.9.0-module-nav/testmocking/web.py", line 88, in add_system
    self.load("/store")
  File "/codedata/code/govready-q-0.9.0-module-nav/testmocking/web.py", line 57, in load
    self._resolve(req)
  File "/codedata/code/govready-q-0.9.0-module-nav/testmocking/web.py", line 45, in _resolve
    self._use_page(match.func(req, *match.args, **match.kwargs))
  File "/Users/greg/Library/Python/3.7/lib/python/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/codedata/code/govready-q-0.9.0-module-nav/siteapp/views.py", line 312, in apps_catalog
    messages.add_message(request, messages.ERROR, "Please select 'Start a project' to continue.")
  File "/Users/greg/Library/Python/3.7/lib/python/site-packages/django/contrib/messages/api.py", line 30, in add_message
    'You cannot add messages without installing '
django.contrib.messages.api.MessageFailure: You cannot add messages without installing django.contrib.messages.middleware.MessageMiddleware
```

**Comment by ethankaminski** [comment]
Opened PR #726 to address this.

**Comment by gregelin** [comment]
Closed with PR #726.

**Comment by gregelin** [comment]
Fixed
