### ISSUE TITLE
Gevent, Python, and Django

### ISSUE THREAD

**Issue by davidpofo** [GovReady/govready-q#1141]
**Describe the issue as a Story**
As a user of Govready, ...
As a GovReady developer, I want to be able to install govready with Django 3.1.3(and possibly 3.1.4) with Python 3.9. I know this complete once gevent has no compatibility issues. So we need to try to install govready-q with Django 3.1.3, in Python 3.6-3.9 environments and with gevent(current version & latest release)

**To Reproduce**
1. Go to a directory in my local file system and git clone govready.
2. pip(pip3) install requirements.txt in a Python 3.9 virtual environment
3. Scroll down through stack trace.
4. See error which mentions gevent 1.4.0 has an incompatibility with Python 3.9

**Expected behavior**
I expect the latest gevent(20.9.0) will not have a compatibility issue with Python 3.9 and Django 3.1.3/3.1.4

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows (WSL)
 - Virtual Machine? No

## Developer hints

Update the version numbers for Django and geven in the requirements.in.
Use the updating shell script requirements_txt_updater.sh to update requirements.txt
Attempt a regular install of Govready with the updated packages.

## Acceptance criteria 

  GIVEN I have updated gevent to v20.9.0 and Django to v3.1.3
  WHEN I install Govready in a Python 3.9 virtual environment
  THEN I will see no errors related to compatibility between gevent, Django, and Python 3.9.

  GIVEN I have updated  gevent to v20.9.0
  WHEN I install Govready using gunicorn with Python 3.9.
  THEN I will see no errors related to compatibility between gevent, Python, and gunicorn

**Additional context**

gevent 1.4.0 only works with Python 3.8 and lower. Might be best to install

**Comment by t-s** [comment]
Working on this. 
Confirmed that `py3.9` throws a `Py_DEPRECATED(3.3)` error when coupled with `gevent==1.4.0` and `django==3.1.4`.
Previously observed that `gevent==1.5.0` with supported Python versions works well.

**Comment by t-s** [comment]
hitting `ImportError: cannot import name 'Context' from 'django.template.base'`, resolving

**Comment by peterkaminski** [comment]
@t-s and @davidpofo, I believe we have been holding gevent to 1.4.0 (and then perhaps also Python 3.x to some extent) because of version dependencies a customer had with CentOS 7.

We may need additional acceptance criteria, and/or we may need to talk about the possibility of a branch or version that would maintain compatibility with CentOS 7.

Greg would know more.

**Comment by bama4** [comment]
Tested GovReady on Windows 10 WSL:
Results:
gevent appears to install successfully.
<img width="1295" alt="Screen Shot 2021-01-17 at 7 09 00 PM" src="https://user-images.githubusercontent.com/5502581/104860712-769cfc00-58fa-11eb-82a4-dd5d7c424de9.png">


On an unrelated note, there appear to be issues with the servers display in the Microsoft Edge browser (Version 87.0.664.75), however:
<img width="1412" alt="Screen Shot 2021-01-17 at 7 16 12 PM" src="https://user-images.githubusercontent.com/5502581/104860363-2f623b80-58f9-11eb-99f2-cc0e08821782.png">

**Comment by gregelin** [comment]
Fixed in `develop` branch. Available in next release.
